version: "3"

services:

  selenium:
     image: selenium/standalone-chrome
     ports:
     - 4444:4444



  api:

    build: .
    image: scrapingg
    command:  uvicorn app.main:app --reload  --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
   
    volumes:
      - ./app:/app
  
    depends_on:
      - selenium 
      - db




  db:
    image: mongo
    ports:
      - 27017:27017
    environment:

            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=rootpassword

    ports:
      - 27017:27017


    volumes:
    - mongo-data:/data/db
    - mongo-configdb:/data/configdb


    command: mongod --port 27017


volumes:
  mongo-data:
  mongo-configdb:  
